// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _sobel_HH_
#define _sobel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sobel_line_buffer.h"
#include "sobel_window_buffer.h"

namespace ap_rtl {

struct sobel : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > input_image_dout;
    sc_in< sc_logic > input_image_empty_n;
    sc_out< sc_logic > input_image_read;
    sc_out< sc_lv<8> > output_image_din;
    sc_in< sc_logic > output_image_full_n;
    sc_out< sc_logic > output_image_write;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    sobel(sc_module_name name);
    SC_HAS_PROCESS(sobel);

    ~sobel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sobel_line_buffer* line_buffer_U;
    sobel_window_buffer* window_buffer_U;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_27;
    sc_signal< sc_lv<11> > line_buffer_address0;
    sc_signal< sc_logic > line_buffer_ce0;
    sc_signal< sc_logic > line_buffer_we0;
    sc_signal< sc_lv<8> > line_buffer_d0;
    sc_signal< sc_lv<8> > line_buffer_q0;
    sc_signal< sc_lv<11> > line_buffer_address1;
    sc_signal< sc_logic > line_buffer_ce1;
    sc_signal< sc_logic > line_buffer_we1;
    sc_signal< sc_lv<8> > line_buffer_d1;
    sc_signal< sc_lv<8> > line_buffer_q1;
    sc_signal< sc_lv<4> > window_buffer_address0;
    sc_signal< sc_logic > window_buffer_ce0;
    sc_signal< sc_logic > window_buffer_we0;
    sc_signal< sc_lv<8> > window_buffer_d0;
    sc_signal< sc_lv<8> > window_buffer_q0;
    sc_signal< sc_lv<4> > window_buffer_address1;
    sc_signal< sc_logic > window_buffer_ce1;
    sc_signal< sc_logic > window_buffer_we1;
    sc_signal< sc_lv<8> > window_buffer_d1;
    sc_signal< sc_lv<8> > window_buffer_q1;
    sc_signal< sc_lv<8> > reg_203;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_81;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_bdd_88;
    sc_signal< sc_lv<1> > exitcond2_fu_209_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_98;
    sc_signal< sc_lv<9> > i_1_fu_215_p2;
    sc_signal< sc_lv<9> > i_1_reg_480;
    sc_signal< sc_lv<10> > j_1_fu_227_p2;
    sc_signal< sc_lv<10> > j_1_reg_488;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_109;
    sc_signal< sc_lv<11> > line_buffer_addr_reg_493;
    sc_signal< sc_lv<1> > exitcond1_fu_221_p2;
    sc_signal< sc_lv<11> > line_buffer_addr_2_reg_499;
    sc_signal< sc_lv<8> > window_buffer_load_1_reg_505;
    sc_signal< sc_lv<8> > line_buffer_load_reg_511;
    sc_signal< sc_lv<8> > line_buffer_load_1_reg_517;
    sc_signal< sc_lv<8> > window_buffer_load_2_reg_523;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_128;
    sc_signal< sc_lv<8> > window_buffer_load_4_reg_529;
    sc_signal< sc_lv<8> > input_image_read_reg_536;
    sc_signal< sc_lv<8> > window_buffer_load_5_reg_542;
    sc_signal< sc_lv<11> > p_neg6_fu_312_p2;
    sc_signal< sc_lv<11> > p_neg6_reg_548;
    sc_signal< sc_lv<10> > p_neg7_fu_334_p2;
    sc_signal< sc_lv<10> > p_neg7_reg_553;
    sc_signal< sc_lv<8> > tmp_20_fu_470_p2;
    sc_signal< sc_lv<8> > tmp_20_reg_558;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_bdd_148;
    sc_signal< sc_lv<9> > i_reg_180;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_bdd_161;
    sc_signal< sc_lv<10> > j_reg_191;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_bdd_173;
    sc_signal< sc_lv<64> > tmp_13_cast1_fu_243_p1;
    sc_signal< sc_lv<64> > tmp_17_cast1_fu_254_p1;
    sc_signal< sc_lv<64> > tmp_4_fu_259_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_bdd_186;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_bdd_205;
    sc_signal< sc_lv<11> > tmp_4_cast_fu_233_p1;
    sc_signal< sc_lv<11> > tmp_12_fu_237_p2;
    sc_signal< sc_lv<11> > tmp_13_fu_248_p2;
    sc_signal< sc_lv<9> > tmp_7_fu_267_p3;
    sc_signal< sc_lv<9> > tmp_5_cast_fu_264_p1;
    sc_signal< sc_lv<9> > tmp_8_cast_fu_278_p1;
    sc_signal< sc_lv<9> > tmp_fu_292_p2;
    sc_signal< sc_lv<10> > tmp_cast_fu_298_p1;
    sc_signal< sc_lv<10> > tmp_7_cast_fu_274_p1;
    sc_signal< sc_lv<10> > tmp_s_fu_302_p2;
    sc_signal< sc_lv<11> > tmp_12_cast_fu_308_p1;
    sc_signal< sc_lv<11> > tmp_9_cast_fu_285_p1;
    sc_signal< sc_lv<9> > tmp_9_fu_318_p2;
    sc_signal< sc_lv<10> > tmp_18_cast_fu_324_p1;
    sc_signal< sc_lv<10> > tmp_9_cast2_fu_281_p1;
    sc_signal< sc_lv<10> > tmp_10_fu_328_p2;
    sc_signal< sc_lv<10> > tmp_10_cast1_fu_289_p1;
    sc_signal< sc_lv<9> > tmp_3_fu_340_p3;
    sc_signal< sc_lv<11> > tmp_3_cast_fu_347_p1;
    sc_signal< sc_lv<11> > p_neg4_fu_354_p2;
    sc_signal< sc_lv<11> > tmp_10_cast_fu_351_p1;
    sc_signal< sc_lv<11> > tmp_5_fu_359_p2;
    sc_signal< sc_lv<9> > tmp_6_fu_375_p3;
    sc_signal< sc_lv<9> > tmp_8_fu_386_p3;
    sc_signal< sc_lv<11> > tmp_15_cast_fu_382_p1;
    sc_signal< sc_lv<11> > p_neg7_cast_fu_397_p1;
    sc_signal< sc_lv<11> > p_neg9_fu_400_p2;
    sc_signal< sc_lv<11> > tmp_17_cast_fu_393_p1;
    sc_signal< sc_lv<11> > tmp_11_fu_406_p2;
    sc_signal< sc_lv<8> > tmp_16_fu_422_p1;
    sc_signal< sc_lv<1> > abscond_fu_426_p2;
    sc_signal< sc_lv<8> > tmp_14_fu_432_p2;
    sc_signal< sc_lv<8> > tmp_17_fu_446_p1;
    sc_signal< sc_lv<1> > abscond1_fu_450_p2;
    sc_signal< sc_lv<8> > tmp_18_fu_456_p2;
    sc_signal< sc_lv<8> > tmp_15_fu_438_p3;
    sc_signal< sc_lv<8> > tmp_19_fu_462_p3;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_st1_fsm_0;
    static const sc_lv<11> ap_ST_st2_fsm_1;
    static const sc_lv<11> ap_ST_st3_fsm_2;
    static const sc_lv<11> ap_ST_st4_fsm_3;
    static const sc_lv<11> ap_ST_st5_fsm_4;
    static const sc_lv<11> ap_ST_st6_fsm_5;
    static const sc_lv<11> ap_ST_st7_fsm_6;
    static const sc_lv<11> ap_ST_st8_fsm_7;
    static const sc_lv<11> ap_ST_st9_fsm_8;
    static const sc_lv<11> ap_ST_st10_fsm_9;
    static const sc_lv<11> ap_ST_st11_fsm_10;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<9> ap_const_lv9_1E0;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<10> ap_const_lv10_280;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<11> ap_const_lv11_280;
    static const sc_lv<11> ap_const_lv11_500;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<8> ap_const_lv8_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_abscond1_fu_450_p2();
    void thread_abscond_fu_426_p2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_sig_bdd_109();
    void thread_ap_sig_bdd_128();
    void thread_ap_sig_bdd_148();
    void thread_ap_sig_bdd_161();
    void thread_ap_sig_bdd_173();
    void thread_ap_sig_bdd_186();
    void thread_ap_sig_bdd_205();
    void thread_ap_sig_bdd_27();
    void thread_ap_sig_bdd_81();
    void thread_ap_sig_bdd_88();
    void thread_ap_sig_bdd_98();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_exitcond1_fu_221_p2();
    void thread_exitcond2_fu_209_p2();
    void thread_i_1_fu_215_p2();
    void thread_input_image_read();
    void thread_j_1_fu_227_p2();
    void thread_line_buffer_address0();
    void thread_line_buffer_address1();
    void thread_line_buffer_ce0();
    void thread_line_buffer_ce1();
    void thread_line_buffer_d0();
    void thread_line_buffer_d1();
    void thread_line_buffer_we0();
    void thread_line_buffer_we1();
    void thread_output_image_din();
    void thread_output_image_write();
    void thread_p_neg4_fu_354_p2();
    void thread_p_neg6_fu_312_p2();
    void thread_p_neg7_cast_fu_397_p1();
    void thread_p_neg7_fu_334_p2();
    void thread_p_neg9_fu_400_p2();
    void thread_tmp_10_cast1_fu_289_p1();
    void thread_tmp_10_cast_fu_351_p1();
    void thread_tmp_10_fu_328_p2();
    void thread_tmp_11_fu_406_p2();
    void thread_tmp_12_cast_fu_308_p1();
    void thread_tmp_12_fu_237_p2();
    void thread_tmp_13_cast1_fu_243_p1();
    void thread_tmp_13_fu_248_p2();
    void thread_tmp_14_fu_432_p2();
    void thread_tmp_15_cast_fu_382_p1();
    void thread_tmp_15_fu_438_p3();
    void thread_tmp_16_fu_422_p1();
    void thread_tmp_17_cast1_fu_254_p1();
    void thread_tmp_17_cast_fu_393_p1();
    void thread_tmp_17_fu_446_p1();
    void thread_tmp_18_cast_fu_324_p1();
    void thread_tmp_18_fu_456_p2();
    void thread_tmp_19_fu_462_p3();
    void thread_tmp_20_fu_470_p2();
    void thread_tmp_3_cast_fu_347_p1();
    void thread_tmp_3_fu_340_p3();
    void thread_tmp_4_cast_fu_233_p1();
    void thread_tmp_4_fu_259_p1();
    void thread_tmp_5_cast_fu_264_p1();
    void thread_tmp_5_fu_359_p2();
    void thread_tmp_6_fu_375_p3();
    void thread_tmp_7_cast_fu_274_p1();
    void thread_tmp_7_fu_267_p3();
    void thread_tmp_8_cast_fu_278_p1();
    void thread_tmp_8_fu_386_p3();
    void thread_tmp_9_cast2_fu_281_p1();
    void thread_tmp_9_cast_fu_285_p1();
    void thread_tmp_9_fu_318_p2();
    void thread_tmp_cast_fu_298_p1();
    void thread_tmp_fu_292_p2();
    void thread_tmp_s_fu_302_p2();
    void thread_window_buffer_address0();
    void thread_window_buffer_address1();
    void thread_window_buffer_ce0();
    void thread_window_buffer_ce1();
    void thread_window_buffer_d0();
    void thread_window_buffer_d1();
    void thread_window_buffer_we0();
    void thread_window_buffer_we1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
